language: perl
perl:
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
before_install:
  - cpanm Test::UsedModules
  - cpanm Devel::Cover::Report::Coveralls
script:
  - perl Build.PL 
  - ./Build build 
  - travis_wait 15 cover -test -report coveralls
after_success:
  - travis_wait 15 cover -report coveralls
notifications:
  recipients:
    - travis-ci.org@azumakuniyuki.org
  email:
    on_success: change
    on_failure: always
